version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: laravel_perf_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel_perf
    ports:
      - "33066:3306"
